name: Diff

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

jobs:
  diff-auth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v5
        with:
          node-version: 22.x
      - uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: ${{ github.run_id }}
          aws-region: us-east-2
      - run: npm ci
      - run: npm run cdk diff TSCSDemoAuthKey
  diff-network:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v5
        with:
          node-version: 22.x
      - uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: ${{ github.run_id }}
          aws-region: us-east-2
      - run: npm ci
      - run: npm run cdk diff TSCSDemoNetwork
  diff-resources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v5
        with:
          node-version: 22.x
      - uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: ${{ github.run_id }}
          aws-region: us-east-2
      - run: npm ci
      - run: npm run cdk diff TSCSDemoResources
